name: Go Linting
on:
  workflow_dispatch:
  pull_request:
  release:
    types: [created]
jobs:

  go-lint:
    uses: estenrye/.github/.github/workflows/golangci-lint.yaml@v0.1.25
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
